import LightXML: free, parse_string
import SeisIO: ChanSpec,
  KW,
  TimeSpec,
  check_for_gap!,
  dtconst,
  endtime,
  fastread,
  fwrite_note!,
  mk_t,
  mk_xml!,
  parsetimewin,
  read_station_xml!,
  split_id,
  sxml_mergehdr!,
  sμ,
  t_win,
  trunc_x!,
  x_inds,
  μs
import SeisIO.Quake: event_xml!,
  fwrite_note_quake!,
  new_qml!,
  write_qml!
