printstyled("  si_units\n", color=:light_green)
@test si_units("m") == "m"
@test si_units("Pa") == "Pa"
@test si_units("m/s") == "m/s"
@test si_units("nm/s") == "nm/s"
@test si_units("m/s**2") == "m/s²"
@test si_units("s^43/s**3") == "s⁴³/s³"
@test si_units("s**10/m^4") == "s¹⁰/m⁴"
@test si_units("s^43 m**-3") == "s⁴³/m³"
@test si_units("s^43 cm^-3") == "s⁴³/cm³"
@test si_units("s^43 cm^-3 V^-4") == "s⁴³/cm³ V⁴"
