import Base: ==, -, *, +, append!, convert, copy, delete!, deleteat!,
  firstindex, getindex, hash, in, isempty, isequal, lastindex, length, merge, merge!,
  push!, read, setindex!, show, size, sizeof, sort!, sort, summary, write
import DSP: filtfilt
import ..SeisIO: BUF,
  FDSNget!,
  FiltDefs,
  FloatArray,
  InstrumentPosition,
  KW,
  SeisData,
  checkbuf!,
  checkbuf_8!,
  checkbuf_strict!,
  clear_notes!,
  code2loctyp,
  code2resptyp,
  code2typ,
  datafields,
  dtconst,
  fdsn_chp,
  fdsn_uhead,
  fill_sac,
  get_HTTP_req,
  loctyp2code,
  note!,
  read_misc,
  read_string_vec,
  resptyp2code,
  show_os,
  str_trunc,
  sμ,
  tnote,
  typ2code,
  unindexed_fields,
  write_misc,
  write_sac_file,
  write_string_vec,
  writesac,
  μs
